### ISSUE TITLE
Consider allowing a subcommand for stats/ resource at rubygems.org

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems.org#1166]
Hello people,

We have this page right now:

https://rubygems.org/stats/

This shows us the top 10.

I am however had also interested in top 20 or top 30.

My proposal is to trigger on:

https://rubygems.org/stats/20

And to show top 20.

You don't have to provide the information for ALL the gems,
but I think top 100 would be nice, or top 50, or even just
top 20.

If this is not worth the time investment, which I can understand, no problem,
just close this issue. I was mostly just curious.

Thanks for reading!

**Comment by dwradcliffe** [comment]
Hey! We're currently revamping the stats system. Once that is complete we will have more accurate stats to show on this page. At that time I think we can easily expand the stats we expose. Until then I don't want to make any changes because anything else wouldn't be accurate. Thanks for the suggestion!

**Comment by s2t2** [comment]
Hi @dwradcliffe let me know if you need/want contributions to the stats revamp. I just got my development environment set up with the intention of working on stats stuff.

**Comment by dwradcliffe** [comment]
@shevegen @s2t2 The new stats pipeline is complete and the stats on that page are now accurate. We can move forward with this idea if you want.

**Comment by dwradcliffe** [comment]
This is now complete!
