### ISSUE TITLE
Change from .erb to .haml to facilitate code reading.

### ISSUE THREAD

**Issue by tomasibarrab** [rubygems/rubygems.org#1218]
I have used HAML on my RoR projects and i've found very easily to read HTML code with Ruby using this gem, i think it would be more readable for developers using it.

**Comment by dwradcliffe** [comment]
Thanks for the suggestion but we're going to stick with ERB. HAML can be useful but ERB is more widespread, slightly simpler, and closer to the vanilla rails way. I'm sure there are lots of people with lots of good opinions about this but I'm going to close this now because I don't want to start a big bikeshed discussion about it.
