### ISSUE TITLE
Version.reverse_dependencies perfomance

### ISSUE THREAD

**Issue by spk** [rubygems/rubygems.org#1508]
Ref https://github.com/rubygems/rubygems.org/pull/945

@sonalkr132 
Using current production database and searching rails with this [gist](https://gist.github.com/spk/20e6c35a004a8657aed0a86ce3d7596d)  on my computer.

Result:

```
Warming up --------------------------------------
reverse_dependencies_name
                       316.000  i/100ms
reverse_dependencies_id
                       293.000  i/100ms
Calculating -------------------------------------
reverse_dependencies_name
                          2.744k (± 9.6%) i/s -     13.904k in   5.114582s
reverse_dependencies_id
                          3.074k (±11.6%) i/s -     15.236k in   5.042729s

Comparison:
reverse_dependencies_id:     3073.5 i/s
reverse_dependencies_name:     2744.4 i/s - same-ish: difference falls within error
```

Also @kbrock [mentions](https://github.com/rubygems/rubygems.org/pull/945#issuecomment-262291006) other leads to improve this query.

**Comment by sonalkr132** [comment]
Hey @spk,

Thank you for the issue :+1: 
Actually I hoping to benchmark [this gist](https://gist.github.com/sonalkr132/516f92c0857811cfb9d8b33096efd888). I am sorry if I wasn't clear :sweat_smile: 
I got following results:
```sh
Warming up --------------------------------------
reverse_dependencies_name
                         1.000  i/100ms
reverse_dependencies_id
                         1.000  i/100ms
Calculating -------------------------------------
reverse_dependencies_name
                          0.325  (± 0.0%) i/s -      2.000  in   6.194087s
reverse_dependencies_id
                         10.413  (± 9.6%) i/s -     52.000  in   5.066023s

Comparison:
reverse_dependencies_id:       10.4 i/s
reverse_dependencies_name:        0.3 i/s - 32.09x  slower
```
Would you agree that this is a reasonable change to make?

**Comment by sonalkr132** [comment]
Hmm.. looks like I am missing something.

**Comment by spk** [comment]
Hi @sonalkr132, the query on your gist is not correct for `reverse_dependencies_id` because its not selecting the reverse deps
Indexes look fine also, do you have other ideas to improve this query ?

**Comment by sonalkr132** [comment]
>  the query on your gist is not correct for reverse_dependencies_id because its not selecting the reverse deps

Sorry. I have corrected it (Check [gist](https://gist.github.com/sonalkr132/516f92c0857811cfb9d8b33096efd888) again). Unfortunately, reducing one table join doesn't reduce the cost because we end up iterating over dependencies and versions table regardless. Check query plan [here](https://gist.github.com/sonalkr132/c29f7972511ff8de803da2dba0b20c5b). It guess it also answers why your gist (where you use id instead of name) doesn't make much of a difference either because that part of query is calculated asynchronously.

> Indexes look fine also, do you have other ideas to improve this query ?

Yeah, it seems query planner is already using indexes whenever it can. So nope! I don't have any other idea. 700-ish ms (for `rails` gem) is slow but again `rails` is 4th most referenced gem as reverse dependency.
