### ISSUE TITLE
[GUIDES] Another Take on the How-To Guide?

### ISSUE THREAD

**Issue by rlue** [rubygems/rubygems.org#1597]
Hi,

I'm a novice developer who read through the official [Make Your Own Gem](http://guides.rubygems.org/make-your-own-gem/) guide and had some trouble grokking how the system worked as a whole. I found it a little too introductory, which left me with a lot of questions as to how much I didn't know.

So after finally figuring out the process on my own, I [wrote up my own beginner's guide](http://ryanlue.com/posts/2017-02-18-how-to-publish-a-gem). It didn't get quite the reception I'd hoped for on the Ruby Mailing List and /r/ruby (a couple people had nice things to say, but otherwise, mostly crickets). Still, I think it could be valuable to other people in my situation.

Would anyone care to take a look and weigh in on whether it might be a valuable addition to the guides? Thanks in advance.

**Comment by jvanbaarsen** [comment]
@rlue I think making a PR with the additions you want to make is always a good idea :-) It's easier to judge code then judge "just an idea". So I would say 👍 Go for the pr :-)

**Comment by shevegen** [comment]
> I found it a little too introductory, which left me with a lot of questions as to
> how much I didn't know.

Was the same for me. I am still somewhat of a semi-noob but I can sort of workaround
things.

I just give you one example of many more.

In the past, I hardcoded the ruby version, rubygem version etc... for my .gemspec file.

But because I myself always use the latest ruby, and the latest rubygem, I actually wondered
how I could simplify it. And et voila!

    s.required_ruby_version     = '>= '+RUBY_VERSION
    s.required_rubygems_version = '>= '+Gem::VERSION
    s.rubygems_version          = '>= '+Gem::VERSION

I have been using that since several months and it is working quite nicely.

(In theory of course I should actually check for backwards compatibility but because I am the number one user of my own gems anyway, I can get away with being lazy here ;D and if people really want to check for downwards compatibility, they can very easily re-build the gem. Most of my ruby code should be backwards compatible, at the least at around ruby 2.1.x or so.)

This is just one example of many more, how to write a GOOD .gemspec actually.

So on this topic, I agree with rlue - I think there could be additional cues provided no matter which ones.

I have only one reservation about the blog entry - while I agree that it adds more information, I think the old tutorial/guide is actually pretty succinct and "to the point", which has both advantages and disadvantages obviously.

My suggestion would thus be this:

- 1) Let's keep a simpler "how to write your own .gem", as a main reference to get things started

and for

- 2) We could have a more advanced guide. I would make that one less centric to any individual per se though. I mean, the authors and contributors can be mentioned of course, but I think the focus of this should be on dealing with advanced things in regards to .gem, or perhaps linking in to some other sites too (I do not know which tools are available since I wrote my own ruby scripts, but there is... gemcutter or jeweller or something? At the least some years ago).

>  It didn't get quite the reception I'd hoped for on the Ruby Mailing List 

The mailing list is unfortunately difficult to navigate for me; and also has quite a lot of spam, and 95% has newbie questions. The latter is fine, but after you have been using ruby for a while, you may not ideally want to always read newbie stuff alone; also there is stackoverflow which is in many ways pretty good.

There are a lot of people commenting on ruby issues though, who may not really be active on the ruby mailing list. :D

**Comment by rlue** [comment]
I appreciate the feedback and will work on a PR as soon as I get finished with some upcoming job interviews. In the meantime, I'd like to submit the criticism that the current official guide conflates the task of _building a library_ with that of _publishing a gem._ In the process, it glosses over a lot of important conceptual background. This may be what @shevegen means when he says

> I think the old tutorial/guide is actually pretty succinct and "to the point"...

but this succinctness comes at the cost of fundamental understanding.

For instance, the official guide suggests that you break a library into multiple files [simply to keep the file from ‘getting crowded’](http://guides.rubygems.org/make-your-own-gem/#requiring-more-files), whereas mine devotes an entire separate post to [the internal file structure of a library, and its correspondence with the library's class hierarchy](http://ryanlue.com/posts/2017-03-03-how-to-structure-a-library). These are things you really should know if you're going to build a library, but the official guide doesn't even hint at the fact that there's an organizational principle at work here.

**Comment by colby-swandale** [comment]
Hi, thanks for opening this issue and offering to help improve the guides. There are some good ideas here and we're welcoming for any improvements to the guides.

But I'm going to close this issue as you want to discuss this over at https://github.com/rubygems/guides where the rubygems' guides are.

**Comment by rlue** [comment]
Thanks @colby-swandale, will do!
