### ISSUE TITLE
High download number...

### ISSUE THREAD

**Issue by cocodevienne** [rubygems/rubygems.org#1629]
So about two days ago (Saturyay) I uploaded a gem to rubygems.org and wasn't really expecting anyone to download it. However, now the download counter says, that my gem has been downloaded 500+ times and I'm kind of wondering if this means that I am gaining a big usership or if that number is in any way fake or distorted! I am not complaining, I am merely quite puzzled.

**Comment by dwradcliffe** [comment]
Could be anything. I've seen test gems being downloaded hundreds of times. Could be bots or real users or anything in between. Sorry I can't give you a specific answer.

**Comment by simi** [comment]
I think rubygems.org custom mirrors are also triggering download increment. I have spotted similar "problem" before also.

**Comment by dwradcliffe** [comment]
@simi good point, that's definitely part of it

**Comment by cocodevienne** [comment]
Hm..so I am not the only person who experienced this, is there any way of finding out who triggered the download? @dwradcliffe @simi

**Comment by dwradcliffe** [comment]
Unfortunately that's not something we provide at the moment.

**Comment by shevegen** [comment]
Yep I think simi's comment is good too. I used to think that most downloads are just bots, but perhaps also sync-mirrors or something downloads stuff too. But also genuine people :) I know because two have emailed me with bug reports very soon after I started rubygems. It would be nice if in the long run one could get some rough estimate on people using stuff or something. I noticed that, if I push-update some gems more regularly then others, then these gems consistently will be downloaded more regularly... so I think that some bots or scripts must also check for some other kind of activity. But I can not really prove anything, I just think that simi's comment and the "behaviour" of downloads, sorta seems to indicate that. What I can definitely say is that there is some difference between gems that you push with new updates often, say every 3 days; and gems that you upload only e. g. 1x per month. The first appears to attract a lot more "trigger-updates" than the latter, even more than 10x times imo (e. g. 3 days in 1 month, 10x updates per month so 10x more downloads ... but it's significantly more than 10x IMO... but again, I have no real dataset or statistics to verify my claim, it's only just some semi-rough estimate on "guessing" here from me really).

**Comment by simi** [comment]
This will not be easy to implement. Maybe it is (it will be soon) possible to calculate client downloads via `gem install` / `bundle install` via User agent.

But you'll still get false numbers from various automated systems like CIs, deploy machines, ...
