### ISSUE TITLE
Adding gem owners is case sensitive

### ISSUE THREAD

**Issue by stve** [rubygems/rubygems.org#1631]
I recently tried adding an owner to one of my gems, using the `gem owner` command but encountered an error:

```
› gem owner <gem> --add Someone@gmail.com
Adding Someone@gmail.com: Owner could not be found.
```

Downcasing the email allowed it to work successfully:

```
› gem owner <gem> --add someone@gmail.com
Owner added successfully.
```

Looking through the code, the API controllers call `User.find_by_name` which does a lookup by `email` and/or `handle`, both of which perform a case sensitive lookup.

Should I be able to add a gem owner via the `gem owner` command (and by proxy, the API) without needing to be concerned about case sensitivity? I realize this is a bit of an edge case so thought I'd ask before working on a pull request.

**Comment by shevegen** [comment]
Hmm. Correct me if I am wrong here - these are two different email addresses that you showcase there right?

I assume that gem tries to find out who the owner is, based on the email at hand.

The above would then constitute a user error, right? Because emails would be case sensitive.

PS: A web-interface would be pretty nifty for adding gem owners to your own projects from the main interface page, but I understand that there may be more pressing issues than web-options. Rubygems.org seems to have gotten a lot more active in the last ~1 year or so; I notice primarily because my most downloaded gem slipped about 200 positions behind other gems that took over. :D

**Comment by stve** [comment]
I should have looked for a specification before opening this. Indeed you are correct:

> The local-part of a mailbox MUST BE treated as case sensitive. Therefore, SMTP implementations MUST take care to preserve the case of mailbox local-parts. In particular, for some hosts, the user "smith" is different from the user "Smith". However, exploiting the case sensitivity of mailbox local-parts impedes interoperability and is discouraged. Mailbox domains follow normal DNS rules and are hence not case sensitive.

Given the above, I don't think this is a problem RubyGems needs to solve.
