### ISSUE TITLE
Translation missing for pt-BR

### ISSUE THREAD

**Issue by duduribeiro** [rubygems/rubygems.org#1834]
Hey folks 👋 

When the user submit the register form for pt-BR, it returns a translation missing error:

![image](https://user-images.githubusercontent.com/771411/48855496-4c436880-ed9b-11e8-923e-9bbeaad29536.png)

It looks like that it isn't loading the translations for the https://github.com/svenfuchs/rails-i18n/ gem. I'm trying to fix it in the code but had no success yet. Any ideas? 🤔

**Comment by duduribeiro** [comment]
Looks like it isn't only for pt-BR. :de is with the same error:

![image](https://user-images.githubusercontent.com/771411/48855689-b52ae080-ed9b-11e8-9cb0-5c2baad831d4.png)

The only one that looks to be loaded on rails-i18n is the `en`.

**Comment by universal** [comment]
Hmm, not opening a new issue, since this seems to be somewhat related. It looks like it is not falling back for translations anymore. So the empty keys for example in the german translation are not "fall backed" by the english ones, but are showing up as missing. Maybe something changed in the i18n/??? gem?
