### ISSUE TITLE
Block users from using compromised passwords

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems.org#2052]
In the past 12 months, several popular gem authors have [had their](https://snyk.io/blog/ruby-gem-strong_password-found-to-contain-remote-code-execution-code-in-a-malicious-version-further-strengthening-worries-of-growth-in-supply-chain-attacks/) [accounts compromised](https://snyk.io/blog/malicious-remote-code-execution-backdoor-discovered-in-the-popular-bootstrap-sass-ruby-gem/) by attackers which resulted in new gem versions being published containing malicious code. In an effort to reduce the risk to users having their accounts compromised, we should block known compromised passwords from being used during signup/password reset.

### Implementation Idea

http://haveibeenpwned.com maintains a very large collection of compromised passwords and provides an API that can check if a given password (anonymized) is safe and secure.

@indirect has written a gem called [unpwn](https://github.com/indirect/unpwn) that contains a copy of the popular passwords, but also queries haveibeenpwned.com as a fallback. We should integrate this as a validation into the user model to check passwords are secure and have not been compromised.

We could also link popular password managers in the signup/password reset fields as well to ensure an even better security practice for users.

**Comment by dwradcliffe** [comment]
👍🏻

**Comment by hsbt** [comment]
I'm 👍 this idea for pushing the new gem release.

But I have a concern. How about http://haveibeenpwned.com is trusted in the world?

**Comment by indirect** [comment]
@hsbt the API does not take a copy of the password—we hash the password and then send only part of the hash. You can read how it works in [the API docs](https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange). 

I further added my gem, creating a bloom filter from [the 1 million most common passwords](https://cry.github.io/nbp/), so we do not even need to contact the API for the most common passwords.

**Comment by rubyFeedback** [comment]
In general I agree with the basic thought behind the idea present by colby, so +1 from me.

There is, however had, one minor concern I have. On reddit some time ago several passwords were compromised, or at the least reddit stated so. As a consequence people were told to have to change their passwords. I refused for various reasons (difficult to explain but mostly it was a combination of me not caring, and not having any interest to go through the hassle of changing password to a password I can not easily remember) and instead ... created a new account.

This sounds a bit excessive user laziness, I am aware of that, but the other thought is that I fail to see why I should want to change a password because upstream forces me to have to do so. I understand the rationale, by the way, but that still does not mean that I do love to change passwords.

I created a new account on reddit which has exactly the same password. This is also strange but it sort of demonstrates that strange point that I am trying to make ...

This situation can not be compared to rubygems of course, because it is different. For example, on reddit I just write stuff, whereas on rubygems I publish code that can be re-distributed by other people. So I understand that there is a difference - in other words, rubygems is more important than reddit for various reasons. :D

Still, though, I in general dislike upstream forcing password-changes. Another minor reason may be that the reddit options formular is so horrible - I absolutely hate that. So it may also be an issue of convenience (I should state that I very rarely use emails, oddly enough; so communication via emails is difficult. I do use issue trackers or phpbb-webforum though - I guess a lot of this has to do with "ease of workflow" for me).

Anyway - the idea is ok but the two comments I have are:

a) consider making any APIs that users use, simple and convenient. For example, either an online-preferences field for rubygems.org users to easily and conveniently change the password, if necessary; or if it can only be done through the commandline variant of gem, to provide simple examples how to do so (I would not know out-of-the-box how to actually change my password ... and I may end up with a situation such as reddit if log in were suddenly no longer possible before I'd be forced to change my password, which might lead to a situation where I have no interest to want to change my password)

and

b) consider the situation of whether users with an account on rubygems.org are forced into this, or not, e. g. what may happen if a user would re-change the password to one that is "compromised". I know that that it is a perfectly valid rationale to state that a compromised password means that a user account can be hijacked at will leading to situations of hostile take-over of accounts, which is evidently bad for any downstream user - but if the rationale by rubgems would be that compromised passwords are invalid, then users would be forbidden from using a compromised password (and changing it back to that old password). Again I understand the rationale very well - I just massively dislike having to use less convenient passwords in general.  I don't have a good solution here, though. How does github handle this by the way? On a side note, gmail also tries to "validate" my password which requires a smartphone number which I don't provide, so I am logged out of there too, excluding my gmail account where my old password works fine without requiring this smartphone-validation. :P

I agree that downstream users have a right to be informed and indicated of any potential problem though, so I have a mixed opinion altogether. I think the by far overwhelming amount of accounts on rubygems.org is by non-malicious folks.

By the way, last but not least, perhaps there may be some additional option for gem/bundler to sort of indicate a more rigorous approach for when wishing to install addons (rubygems) - e. g. to preserve the old way, but to also allow for stronger setups where the downstream user indicates what he wants to have, e. g. including what colby wrote here - but I digress; this may be for a long-term thought for more "security and trust", however we want to define these terms.

**Comment by eliotsykes** [comment]
👍 for unpwn to protect against compromised passwords being used in the future.

For existing passwords, could we consider using public breach data to detect vulnerable accounts and reset only those? There's some detail about how Basecamp did this here: https://rework.fm/did-you-order-the-code-red/ (scroll down to `[00:08:52]` in the transcript).

**Comment by matiaskorhonen** [comment]
I recently pushed #2080 to prevent users from adopting compromised passwords.

My PR doesn't address how to handle existing accounts with compromised passwords.

**Comment by dwradcliffe** [comment]
I think this is done now?

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems.org/pull/2082
