### ISSUE TITLE
Remove emails from public profiles

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems.org#2055]
Evidence from the logs suggests that attackers are gaining access to user accounts on rubygems.org by first compromising a user's email account, and then perform a password reset.

In an effort to help protect users and prevent attackers from gathering infromation, we should no longer show user's email address on the public profile pages. 

If users wish to continue having contact information on the profile pages, we could look into adding a Github & website links to profile pages instead.

**Comment by rubyFeedback** [comment]
Hmm. I understand the use case and I think it is a fine use-case, too; however had I think it should also be taken into account that some folks would like to show/display email there anyway, in the event that they may want to be contacted by real people. (It's probably not a high priority, because we can already add our email into e. g. the README.md file that can be distributed with a gem, but I think it may still be better to have this controllable by the ruby user at hand. Also - not everyone is using github via a website. For example, most of my gems at rubygems.org have documentation at rubygems.org, e. g. autogenerated README.md files, but I do not have active websites for these gems at github, mostly because it would impose too much work).

Perhaps this could be made a toggle - remove it by default, but allow users to display email at their own discretion somehow, be it via the web-interface, or via the gem commandline. I personally actually do not even need this, since we can already provide our email in a README.md file, but I am thinking more generally. It is however had probably not of high priority. The only point I wanted to really extend here was that the alternative to link towards github or other websites is not always applicable - I am quite active on rubygems.org with my gems, but I am actually notoriously inactive elsewhere, oddly enough. So the replacement would not work in my case - but I also admit that I don't need the contact-email at the profile page either since we can put this information into a markdown file, so feel free to disregard my comment altogether. :)

Having it an option that could be controlled by the user would be better either way, though, IMO; and to require of people to enable this specifically.

**Comment by hsbt** [comment]
I'm not sure this improves the security level. Because the attacker can try to login with a compromised password to all of the users of rubygems.org used password list.

And we completely lost to access way for their contact address without github or website links. Ex. When I hope to take over the old gem from them, I don't see their contact address after this idea.

**Comment by indirect** [comment]
GitHub also shows email addresses on profile pages, so I'm not super sure this is actively improving security? There's also the related issue of every gem having an email address in the gemspec, so it's not exactly a secret even if we hide it on this page.

**Comment by mensfeld** [comment]
You can also get the email from the metadata, gemspec and other places. See: https://diff.coditsu.io/diffs/8e89bcb5-4e80-44e4-9281-f19cdb699a00#d2h-004177

**Comment by sonalkr132** [comment]
Hi @colby-swandale , thank you for your concern. I am closing this as it isn't clear by doing this would help with our security. 
The option of showing email publically is configurable.
