### ISSUE TITLE
Mention yanked versions exist in search

### ISSUE THREAD

**Issue by eliav-lavi** [rubygems/rubygems.org#2110]
I've recently released a new gem called Dawn.

As I did in the past, I checked on RubyGems before I even picked the name, to make sure it is available on it's purest form (i.e. just "Dawn"). Since no result was found, I happily went on with it and released it. I then checked out my new RubyGems page, and found out I have version history, which I clearly do not... It turned out there was a gem called "Dawn" before, and it has been yanked, thus it did not appear on the search results.

Had I known the name was used in the past by a gem which is now yanked, I might have chosen a different name, to avoid confusion.

Perhaps search should not hide yanked gems completely, but mention they do exist in some manner?

**Comment by rubyFeedback** [comment]
> It turned out there was a gem called "Dawn" before, and it has been yanked, thus it
> did not appear on the search results.

I agree with you; I actually came to something similar as you, although from a different path.

I used to have lots of gems (almost 150), but have since then removed many, so I am down at about 79. I mostly integrated the smaller gems (most of them were tiny, really), into larger projects. Anyway - one project I wanted to actually rename, but back then it was not so simple to remove things; e. g. that was before the 100 days delay was added. So a few years ago or so.

I then tested the 100 days delay, and re-pushed the same gem with the same name but a higher version - and, lo and behold, all the old yanked versions re-appeared. (One reason why I did this was because I had like 1500 yanked releases, and I felt that this cluttered the page. :P ) 

So anyway, I found that this was a bit annoying but not worth to report it since, to me, it was mostly a cosmetic problem rather than affect anything.

If I understand your issue request here, though, then this means that this indeed actually affects the usability of rubygems - that is, in your case, by picking a different name perhaps.

I do not know whether search should hide yanked gems completely, but I think there may have to be a reconsideration of whether yanked gems are removed or not. I don't mind if they are still kept at some rubygems.org server, but on the other hand I feel that yanked gems should perhaps be completely wiped altogether (I don't know if another user would see the old yanked history too, or whether this appears only if the same user does so).

> found out I have version history, which I clearly do not.

Actually, re-reading your comment, it seems as if others also see that yanked history.

I would suggest to either completely remove the history (delete it from the database); or if the rubygems team wants to keep it, to move it to some other place where new users and new developers are not affected by yanked versions of past releases or different ruby users (actually I think this was just a slip up in the design consideration, so perhaps the design specification should include that; perhaps there is some feature that I forgot or did not see, but anyway, I am sure the rubygems team can decide what to do - I am just giving some of my opinion and past experience here :) ).

PS: Giving gems a good name is important, for many reasons! I can't stress this enough.

PSS: Actually, your issue could be resolved in two ways, right? Either by improving search; or by removing all old yanked versions completely, correct? Just asking, since perhaps one of the two solutions may be easier for the rubygems team to implement. Simplicity rules. :)

**Comment by eliav-lavi** [comment]
Thank you for your reply! Indeed, my main concern was the misleading [version history page,](https://rubygems.org/gems/dawn/versions) visible to visitors and other users as well. If you visit the former link, you can see 3 versions - only the last one is related to my work...

I think removing yanked versions completely is a bigger issue, I guess there is a rationale behind keeping them? Improving search feels like the more natural way to resolve this issue, but I am not entirely sure here.

**Comment by dwradcliffe** [comment]
Gem versions are immutable. A single version of a gem will always be the same from the day it was published until forever. If we abandon that tenant users will never know if they have the right version, we would be open to more security issues, and indexing will break.

That said, I understand how this would be frustrating, both at the time you searched and now that you have versions from (essentially) another gem in your history. We should figure out a way to make this clear in the search UI. I'm open to ideas. :)

**Comment by eliav-lavi** [comment]
I think the smoothest solution would be showing up yanked gem versions in search. As far as I am concerned, had I known there was a gem named Dawn before, even if currently completely yanked, I would have picked another name. But I don't think I could have known that. So, I think search UI is the way to go.

**Comment by keithrbennett** [comment]
Would it make sense to wipe out all traces of a yanked version from the DB? (Isn't that what a gem author really wants to do when yanking?) And remove the gem entirely from the DB when there are no longer any nonyanked versions remaining? Wouldn't this solve this issue and the recently closed issue I reported (https://github.com/rubygems/rubygems.org/issues/2013)? If it's necessary to keep an audit trail, perhaps that can be done using a different table in the DB?

**Comment by sonalkr132** [comment]
> If it's necessary to keep an audit trail, perhaps that can be done using a different table in the DB?

we not only want audit trail but we want to keep versions immutable too. After a user had packaged their application with a specific version, the code **must not change**. failing to build the app is expected/desired when an existing version is removed.
