### ISSUE TITLE
Typo-squatting packages on RubyGems

### ISSUE THREAD

**Issue by lingfennan** [rubygems/rubygems.org#2115]
The 38 packages published by user `coffeetocode` typo-squats popular packages such as the recently compromised `rest-client`. The corresponding package published by `coffeetocode` is `restclient` and has been downloaded 71K times. Not sure if this should be allowed or removed, so posting here to raise attention.

These packages currently don't contain malicious code and claim to be typo guards. They belong to the protect list proposed by @sonalkr132 at https://gist.github.com/sonalkr132/af05b030af793ce17a69245152d5aa5f.

https://rubygems.org/gems/restclient
https://rubygems.org/profiles/coffeetocode

**Comment by rubyFeedback** [comment]
I am not sure if these can be called as typo-squatters. For example, https://rubygems.org/gems/restclient mentions "gem install rest-client".

It is a fake-gem, with content such as:

raise 'This failure is intentional. You probably meant to install and run rest-client' 

But what if there are simply differences in names alone? Not everything can be considered a typo-squatting automatically, and it can bring in real problems such as the one reported by another user some time ago in regards to the typo-squatting algorithm detecting false negatives.

Then there is also the issue of reserving a namespace. This actually has affected me. I have a gem called "configuration", toplevel namespace is module Configuration. I can not upload this gem because someone else already occupies that namespace.

I understand that this is also somewhat related to ruby not having "strong" namespaces (e. g. one "module Configuration" will be global), but at github we don't have this limitation; and bundle works fine with people naming their gems in any way (I am not sure how bundler does it though).

Perhaps there may have to be a different policy for rubygems.org, e. g. something like "gems should be somewhat useful for some particular purpose, including testing how to make gems" - and then with a somewhat loose definition, obvious typo-squatters but also useless packages such as the one by coffeetocode, could be removed. But what then? What if another one wants to upload a different package?

I think it may also be important to actually focus on what is used by many people first. Gem downloads of 53 times, even for typo-squatters, are probably not that important, compared to, say, 100 million download gems. It's not so trivial in my opinion either way how you look at it, and how you want to resolve something. This is why I think: "Not sure if this should be allowed or removed, so posting here to raise attention." is problematic, because you'd have to ensure the same policy in the future, right? Or do you only mean to refer to code that is obviously meant as "typo protecting"? IMO manual investigation may tap away time that could go into fixing other bugs or polishing the UI etc...

**Comment by sonalkr132** [comment]
We tried maintaining a protect list using  levenshtein distance. It had too many false positive. 
Issue is being tracked at #2058, please leave your comments there.
