### ISSUE TITLE
Should we tell contributors to turn off elasticsearch security, or explain how to set it up?

### ISSUE THREAD

**Issue by nateberkopec** [rubygems/rubygems.org#2156]
CONTRIBUTING.md says:

`docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.1.2`

But the default is that token auth is enabled. We can disable it with `-e "xpack.security.enabled=false"`, but IDK if that's appropriate or not.

In either case, I think we should explain how to set up the auth for the docker container properly (IDK how to do that) or change the command in the guide to disable xpack security.

**Comment by simi** [comment]
Was this changed recently at elastic side? I remember I had no problems using this few weeks ago. I can recheck.

**Comment by simi** [comment]
I was looking into this. I had problems using elasticsearch 5.1 and 5.2 docker images. I had to use 5.3+ (because of https://github.com/elastic/elasticsearch/issues/23218). Not sure if we need to update elasticsearch version as well. Anyway I had to provide `-e "xpack.security.enabled=false"` otherwise connections got rejected.

I agree when following current steps I wasn't able to start dev. environment. I think we can disable auth token in recommended docker run command and mention potential danger in CONTRIBUTING.md.
