### ISSUE TITLE
big, realy big repository (security)

### ISSUE THREAD

**Issue by 0xtrzy** [rubygems/rubygems.org#2334]
What happened when I create a repository, put it to rubygem
and add big files and delete it?

Ruby gems is resistant to this kind of garbage disc?

**Comment by sonalkr132** [comment]
We have set [`client_max_body_size` to 500M](https://github.com/rubygems/rubygems-infrastructure/blob/7b2bedec0d5b08f02d6b3bcde162304f10c0daa3/cookbooks/rubygems-balancer/templates/default/site.conf.erb#L215) but it doesn't seem to be working as expected. If you try to upload a really big gem file, it is most likely you will receive 503 because of proxy timeout of 60s. As far as I see it, only limit on upload size is upload speed of the client.

**Comment by 0xtrzy** [comment]
@sonalkr132 I'm not talking about big gem
but BIG git repository. 

For example git directory are 1GiB but repository are small.

**Comment by dwradcliffe** [comment]
We don't host git repositories.

**Comment by simi** [comment]
@0xtrzy rubygems.org doesn't host any git repositories.

**Comment by 0xtrzy** [comment]
@simi @dwradcliffe thx
