### ISSUE TITLE
Add gem to "API key was published in a public gem" mail

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems.org#2462]
I just got that mail and have no idea which gem had my api key, so this might happen again if I don't find out how this happened :(

**Comment by sonalkr132** [comment]
My bad. I reused [reset_api_key](https://github.com/rubygems/rubygems.org/blob/master/script/reset_api_key) for an incident unrelated to "API key was published in a public gem".
To clarify, your API key was not reset because it was published in a public gem. I guess I will resend the clarification. Thank you for bringing this up.

**Comment by grosser** [comment]
thx for the quick reply, I can stop looking through my gems now :D

**Comment by sonalkr132** [comment]
I am closing this. As of now, resetting API keys is a very manual process. Your suggestion was duly noted. I will send PR to make the mailer view a bit more generic and keep looking into ways of adding more info to it.

**Comment by jamgregory** [comment]
Hello,

I received this email as well - just wanted to check when the clarification of the incident will be available?

Thanks!

**Comment by sonalkr132** [comment]
We are still in the process of investigating the issue, I think we will decide when and how we will disclose this after we have checked all boxes from our side.
We have reset your API key as a precautionary step.

**Comment by sonalkr132** [comment]
https://blog.rubygems.org/2020/07/28/api-key-leak.html
