### ISSUE TITLE
Webhooks are not firing using `fire` endpoint and upon version releases

### ISSUE THREAD

**Issue by KaanOzkan** [rubygems/rubygems.org#2741]
## Steps to Reproduce

1. Create an account, write down the API key
2. Register a webhook: 
  ```
     curl -X POST -H 'Authorization:***' \
       -F 'gem_name=*' -F 'url=https://webhook.site/f7e3eaff-8b3e-4c9d-a9a6-c5e2f665fe99' \
       https://rubygems.org/api/v1/web_hooks
  ```
3. Fire the webhook:
  ```
     curl -H 'Authorization:***' \
       -F 'gem_name=*' -F 'url=https://webhook.site/f7e3eaff-8b3e-4c9d-a9a6-c5e2f665fe99' \
       https://rubygems.org/api/v1/web_hooks/fire
  ```

## Expected Behavior

Successful firing of the webhook using `fire` and visible request to [this webhook test site](https://webhook.site/f7e3eaff-8b3e-4c9d-a9a6-c5e2f665fe99) upon a new gem version release.

## Current Behavior

`fire` endpoint returns a `500`:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link href="/stylesheets/static.css" rel='stylesheet' type='text/css'>
    <title>Server error | RubyGems.org</title>
  </head>
  <body>
    <div class="wrapper">
      <div class="image__wrapper">
        <img height="530" alt="500 error" src="/images/sea_level.svg">
      </div>
      <div class="content">
        <h1>Server error.</h1>
        <p>
          Looks like something blew up on our end. We&rsquo;ve been alerted of the problem, but feel free to open up an
          <a href="mailto:support@rubygems.org">issue</a>
          if you want it fixed faster.
        </p>
        <a href="/">Back to RubyGems.org →</a>
      </div>
    </div>
  </body>
</html>
```
And no requests have been sent to the webhook URL after about a day.

## Environment
Browser and its version:
RubyGems version:

## Additional Context

I noticed this open issue regarding webhooks https://github.com/rubygems/rubygems.org/issues/1434. However, I'm consistently getting failures.

I have also confirmed webhooks are registered from the `https://rubygems.org/api/v1/web_hooks.json` endpoint.

Thank you 🙏

**Comment by sonalkr132** [comment]
Hi KaanOzkan. 
The error is being raised because we are using `user.api_key` in [the webhook](https://github.com/rubygems/rubygems.org/blob/master/app/models/web_hook.rb#L20
), which is nil for new users:
```
job = Notifier.new(url, protocol, host_with_port, deploy_gem, version, user.api_key)
```
We stopped setting user.api_key since https://github.com/rubygems/rubygems.org/pull/1962 (`generate_api_key` was removed from users). To fix this, we need to create a new scope (webhook auth) for api_keys which will be store it in plain text and used exclusively for webhook authentication header.
This is a known issue, although low priority for me at the moment. If anyone else wants to fix this that would be great.

I have manually set user.api_key for your user and you should no longer be receiving the error.

**Comment by simi** [comment]
This problem is solved, since webhook api key is not required (even it is highly recommended to be set). The logic for api key selection is currently at model. https://github.com/rubygems/rubygems.org/blob/22625f39e4b3a6159635c2ffa688a88ef476ad6c/app/models/web_hook.rb#L33-L35

But even with no API key present, hook is fired with following hash.

https://github.com/rubygems/rubygems.org/blob/22625f39e4b3a6159635c2ffa688a88ef476ad6c/app/jobs/notify_web_hook_job.rb#L46-L48
