### ISSUE TITLE
Method to retrieve full list of gems

### ISSUE THREAD

**Issue by dmarkow** [rubygems/rubygems.org#313]
In putting together a site that integrates with RubyGems using the web hooks stuff, it'd be nice to be able to seed my database with a complete list of *all* the gems, not just "owned gems". Short of using the command line (something like `gem list --all --remote`) and then requesting the details of each gem one at a time, would it be possible to have an API request to pull this full list? Maybe cached once per day or something?

(I can write a patch/pull request for this, but didn't want to spend time doing that if there was a reason it wouldn't be accepted).

**Comment by qrush** [comment]
I am still :+1:. As mentioned in #980, it sounds like a great time to make a v2 API!

**Comment by ETetzlaff** [comment]
This issue hasn't been updated in quite some time, nor have I seen any advancements in the v2 API section.  I'm unclear as to what the game plan is for v2 of the API and currently have a dev version working through v1 of the API since no routes have really been set in stone for v2 it's looking.  

I went and reviewed the total count of gems on the site and it's just over 100k, I can't imagine this is going to be terrible as it's just a dump of data.  

I can toss this up as  PR when I have the tests written around it, or if anyone can clue me in on v2 works I can integrate it with someone there.

**Comment by dwradcliffe** [comment]
There are no plans for a brand new v2 api. We are adding v2 api endpoints when we need to change code or functionality. (See #980)

**Comment by ETetzlaff** [comment]
@dwradcliffe Alright that would make sense.  I'm guessing new development should go in there too.  I just don't see any end points in the v2 section already so I'm no sure what the convention is that people are wanting to follow for those end points.

**Comment by dwradcliffe** [comment]
The new index includes an API endpoint with the full list of gems.
https://index.rubygems.org/versions

Closing since I think that satisfies the need and this is so old. Please comment if I'm missing something.
