### ISSUE TITLE
Website ignores Accept-Language header.

### ISSUE THREAD

**Issue by rkh** [rubygems/rubygems.org#3259]
## Steps to Reproduce

1. Be in Switzerland (which has four official languages).
2. Set everything to English, make sure your browser sends the Accept-Language header to `en-US,en;q=0.5` or similar.
3. Navigate to [rubygems.org](https://rubygems.org)

## Expected Behavior

Website should be in English.

## Current Behavior

Website is in German.

## Possible Solution

Remove whatever logic decides that the website should be in German.

## Environment
Browser and its version: Firefox 106.0.5 (64-bit)
RubyGems version: N/A (3.3.24, but irrelevant)

**Comment by simi** [comment]
Hello @rkh! Since I can't travel to Switzerland to reproduce at the moment, would it be possible to share snapshot of all non-sensitive headers sent to be able to reproduce locally?

We do decide in here https://github.com/rubygems/rubygems.org/blob/c1002efc0eb326d20e88bae60c040463f60dae58/app/controllers/application_controller.rb#L90 which is based on `HTTP_ACCEPT_LANGUAGE` header.

**Comment by rkh** [comment]
Uh actually, this is stupid, I cleared my session cookie and that did the trick. Super sorry about the noise (many other websites do GeoIP stuff and I find it very annoying). I should have investigated more before filing the ticket.
