### ISSUE TITLE
Link to a change log from gem page

### ISSUE THREAD

**Issue by olivierlacan** [rubygems/rubygems.org#578]
I think gem pages should include or at the very least link to change log information about releases (versions). 

Here's what it could look like: 
![image](https://cloud.githubusercontent.com/assets/65950/4914904/45d7a15a-64c9-11e4-9703-50f22be35d51.png)

Note: I've edited this original post after the fact, so the comments from @evanphx and @gaurish are not really relevant anymore. Sorry.

**Comment by shevegen** [comment]
Also +1 from me as an optional thing (non-mandatory). For most of my gems I will not need any changelog, since it is small and barely anyone else uses it. But a very few of my larger gems, may sometimes benefit from a changelog, in particular if it is a larger change e. g. version 1 to version 2, so an entry for it would be nice, hence +1.

**Comment by jvanbaarsen** [comment]
Can probably be closed by https://github.com/rubygems/rubygems.org/pull/1553 
/cc @dwradcliffe

**Comment by dwradcliffe** [comment]
Yep!
