### ISSUE TITLE
Reduce file size of repo

### ISSUE THREAD

**Issue by qrush** [rubygems/rubygems.org#610]
A fresh clone of rubygems.org is over 400MB. What can we do to reduce this? @sferik any ideas? :)

```
[master][~/Dev/rubygems.org] du -skh .
421M	.
```

**Comment by arthurnn** [comment]
Ok, I think I found the best of both worlds, let me show the results and explain after:

```
[arthurnn@ralph arthurnn_rb]$ du -skh .
 11M	.
[arthurnn@ralph arthurnn_rb]$ ls vendor/cache/
[arthurnn@ralph arthurnn_rb]$ more .gitmodules
[submodule "vendor/cache"]
        path = vendor/cache
        url = git@github.com:arthurnn/rubygems.org-vendor.git
```

You can see that the repo, right after a clone has only 11M !!! And vendor/cache is empty as it is a submodule.
How it works is, after you clone the repo you have 2 choices:
- `bundle install`, and carry on (assuming you wont be changing gems)
- `git submodule init; git submodule update` which will clone the big(500M) repo, assuming you need that to change gems.

Like that we can have people cloning the main repo super fast and making changes, and also we have a vendor cache for all gems, with history.

You can test all that locally, clone my fork: https://github.com/arthurnn/rubygems.org.
The gem vendor cache folder is a separate repo, https://github.com/arthurnn/rubygems.org-vendor , which I kept all history that touched that folder.

Just for info, the folders I removed from history were:
- vendor/bundler_gems 
- vendor/gems 
- vendor/rails 
- vendor/plugins 
- vendor/cache

Let me know if you guys like it, and pros/cons about this approach. Only cons we need to consider is that all SHA now are new, and any GitHub link or comment that ref a SHA we wont be able to track that down, but thats what happens when we rewrite history, at least we do this now.

**Comment by indirect** [comment]
This is exactly my suggestion, so I am :+1: on it. :)

**Comment by dwradcliffe** [comment]
Looks good - I think this is the best solution. Let's get a :+1: from @qrush, @evanphx and @sferik before we do it.

**Comment by arthurnn** [comment]
yes,also before rewriting all history, we could save a fork of this repo just in case we need some reference, or backup.

**Comment by qrush** [comment]
So now we have to make sure `git clone --recursive` ? Everytime I've dealt with submodules it's awfully painful and confusing. But I'd say that is better than a huge repo.

**Comment by arthurnn** [comment]
@qrush only people that are going to update gems will have to `git clone --recursive`. which is probably 15% of devs. The other 75% will install gems using bundler and dont need the submodule.

**Comment by qrush** [comment]
I think this one can be closed now. Big thanks to @arthurnn @dwradcliffe and others who helped make this happen!!

**Comment by phoet** [comment]
@arthurnn :kissing_heart:

**Comment by sferik** [comment]
A new patch version of the `bcrypt` gem was just released and I just updated rubygems.org and the vendor repository. I just want to make sure I’m following the correct protocol for updating gems. Here is a script of what I did:

```
git clone git@github.com:rubygems/rubygems.org.git
cd rubygems.org/
cd vendor
git clone git@github.com:rubygems/rubygems.org-vendor.git cache
cd ../
bundle update bcrypt
cd vendor/cache/
git add -u bcrypt-3.1.9.gem
git add bcrypt-3.1.10.gem
git commit -m "Update bcrypt to version 3.1.10"
git push origin master
cd ../../
git add Gemfile.lock
git add vendor/cache
git commit -m "Update bcrypt to version 3.1.10"
git push origin master
```

Here are the two resulting commits: https://github.com/rubygems/rubygems.org-vendor/commit/a64c6d332be068e1bfa17652efac7fedacbd228a and https://github.com/rubygems/rubygems.org/commit/e0c7549b85a48440ceb5c86c8854ca8ab9f0d03c.

Does this all look kosher? Am I missing any steps? Am I performing any unnecessary steps?

If this looks good, I will probably write a small `rake` task so I don’t have to perform 15 steps every time I want to update a gem. Once I do that, should I add it to `lib/tasks`? I could also document this in the [wiki](https://github.com/rubygems/rubygems.org/wiki).

**Comment by arthurnn** [comment]
@sferik seems right. 
However I am not sure if a rake task is necessary.
After you have the repo cloned, there is 2 extra commands only ( which are the commit and push from inside the vendor/cache folder ).

This is me doing a end-to-end gem update:
http://showterm.io/3f29906f765569bc48742

Also, I would say we dont need to update the submodule for every gem we update, we actually could only update the submodule before we merge to production branch.
So people that create a PR to update a gem, they wont need to deal with submodules at all.

**Comment by sferik** [comment]
> Also, I would say we dont need to update the submodule for every gem we update, we actually could only update the submodule before we merge to production branch.

Okay, we just need to make sure this is part of our deploy process to ensure that the `Gemfile.lock` and `vendor/cache` don’t get out-of-sync. /cc @dwradcliffe

**Comment by dwradcliffe** [comment]
Yeah I suppose we could automate the vendor part so no one has to do it manually.

**Comment by mockdeep** [comment]
One thing I've seen in the past is that it is possible for someone to unwittingly re-introduce the files. Not sure if git is better about managing it now, but I think if you were to merge the old with the new it would end up showing each commit twice in the history as well as the files being back in the repo. Doing this on another project, I removed all of the contributors and made them make a pull-request to confirm they were clean before adding them back.
