### ISSUE TITLE
Include README.(md | rdoc | ...) writeup on Gem page

### ISSUE THREAD

**Issue by ianks** [rubygems/rubygems.org#891]
Currently when searching a Gem, you land on a page that gives some metadata about the Gem. However, I find the amount of information to be somewhat limiting, and encourages me to go elsewhere to find out more information about the Gem.

Proposed solution: include a rendered README.* on the page. This would be simple to implement, and would help a lot with giving some interesting content for the Gem pages.

The workflow would go something like this:

1. Check the root of the gem to see if there is a README file
1. If not, check to see if the homepage is a Github repo, if so, use that. 

Thoughts? I would be happy to work on this if it is of interest to others. Just let me know what you think so I don't waste time implementing something this is undesirable.

**Comment by maclover7** [comment]
Sounds like a good idea. A bunch of other package managers (NPM, CocoaPods) have recently introduced this feature.

**Comment by dwradcliffe** [comment]
I'm not sure we want to be pulling in external content other than from the gemspec. This could introduce all sorts of rendering and security issues.

**Comment by qrush** [comment]
I am -1 about this. The gemspec summary/description is enough. Let GitHub (and whatever comes next) worry about markdown rendering, etc.

**Comment by ianks** [comment]
Fair enough, although it's the reason I almost never use rubygems.org, and
I do use npmjs.com often because I can get more information in one place.
Surely something to consider.

**Comment by epitron** [comment]
I wholeheartedly agree! Having the gem's README on the page would be excellent.

The description rarely gives you enough information to know if you want to install this gem, and the links on the side are irritating because the github link is sometimes "Homepage" and sometimes "Source code".

I looked into implementing this feature the other day, and the primary concern is where to cache the unparsed README files (S3? The database? Nowhere, pulling them out of the tarball on demand?)
