### ISSUE TITLE
owners API endpoint not returning owners (sometimes)

### ISSUE THREAD

**Issue by AaronLasseigne** [rubygems/rubygems.org#927]
It looks like there are times the owners are listed but not returned via the API.

https://rubygems.org/gems/tzinfo
![tzinfo rubygems org your community gem host - vimperator 2015-04-03 18-32-12](https://cloud.githubusercontent.com/assets/297205/6990334/c2cb25b6-da2f-11e4-9281-ef18a2b97091.jpg)

```sh
> curl https://rubygems.org/api/v1/gems/tzinfo/owners.json
[{}]%
```

This also appears to be happening for [thread_safe](https://rubygems.org/gems/thread_safe).
![thread_safe rubygems org your community gem host - vimperator 2015-04-03 18-34-06](https://cloud.githubusercontent.com/assets/297205/6990348/059b25f8-da30-11e4-9623-2d66437ca05f.jpg)

```sh
> curl https://rubygems.org/api/v1/gems/thread_safe/owners.json
[{},{"email":"headius@headius.com"},{"email":"thedarkone2@gmail.com"}]%
```

**Comment by arthurnn** [comment]
Good catch. This is most likely because of my change on https://github.com/rubygems/rubygems.org/commit/309908d17f472797d832e4e3a490981cfde6e5a0 .
We should still hide email, if the user opt-in to hide it, but I think we should add the handle in the API, so the hash doesnt look empty like this.
I will fix this. thanks
