### ISSUE TITLE
Stats page shows out of date top ten gems

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems.org#947]
The code that selects the top ten gems on the stats page is querying postgres instead of reds. To get the actual top ten gems, you need code that looks something like this:

```ruby
counts = {}
names = Rubygem.pluck(:name)
names.in_groups_of(100).each do |g|
  counts = Redis.current.multi do |r|
    g.each do |n|
      r.get Download.rubygem_key(n)
    end
  end
  g.zip(counts).each{|n,c| counts[n] = c }
end
counts.sort_by{|x| -x.last.to_i }.first(10)
```

**Comment by qrush** [comment]
This is still a bug. Why didn't #961 fix it?

**Comment by farukaydin** [comment]
@qrush actually it fixed but we had to revert it because of poor performance. I'll work on this issue with production data.

**Comment by farukaydin** [comment]
I worked on this issue and conclude that we're keeping rubygems downloads count in redis as string data like ```"downloads:rubygem:{rubygem_name}" : 1232```. Getting all key values and sorting with ruby is not enough for performance as we saw in previous pr that I submit. We should use redis sorted set like we used to keep version downloads data. 

Copying all string keys to sorted set once is first option but we have to plan a few minutes scheduled maintenance which I personally don't prefer. Another option is we can check gems downloads count in redis with Download.incr method. If any gem downloaded and not included in new sorted set, we copy the rubygem downloads value to new sorted set with increment, otherwise we just increment sorted set gem value. Bythisway, we copy most of the gems eventually without any downtime, and with another pr I can contribute to stats page according to new sorted set.

I need some feedbacks on this issue.

**Comment by arthurnn** [comment]
I was wondering if we could use Postgres data link feature here. https://blog.codeship.com/heroku-data-links-postgres-redis/ . So we only query Postgres, and it would know the right counter using redis info too.
Besides that, I think we should rollup those counters from redis to DB, in a day-basis maybe.

thoughts? (btw, I can help on this too, if you are busy)

**Comment by farukaydin** [comment]
@arthurnn I'm not sure if I work on it within the next days since I've a cold. So feel free to contribute it. Thanks.
