### ISSUE TITLE
Replace rr gem with minitest mock

### ISSUE THREAD

**Issue by arthurnn** [rubygems/rubygems.org#981]
As far as I can tell, we can use minitest built-in stubs, instead of using `rr` gem. as it is not maintained anymore.

**Comment by farukaydin** [comment]
@arthurnn I think we should use mocha gem instead of minitest mock and stubs, since it's more suitable for our needs. In minitest we stub a method and inside of this stub block we have to check assertion, however some of our tests have three stub methods sequentially and after all these stubbed we check the assertion. So if we don't want to check assertion inside of block everytime we use stub, we can go with mocha. What do you think about?

I'd like to work on this issue.

**Comment by arthurnn** [comment]
Sure. mocha works for me too.. Go head @farukaydin . thanks

**Comment by u2** [comment]
#990

**Comment by arthurnn** [comment]
thanks all
